"""empty message

Revision ID: 3a717282ad63
Revises: 527aea607009
Create Date: 2022-03-08 16:22:56.405993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a717282ad63'
down_revision = '527aea607009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('created_ts', sa.String(length=120), nullable=True, server_default=sa.func.now()))
    # op.alter_column(sa.Co)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_ts')
    # ### end Alembic commands ###
