"""empty message

Revision ID: 912be1c5ef93
Revises: d6594a4f3829
Create Date: 2022-03-08 23:25:03.956943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912be1c5ef93'
down_revision = 'd6594a4f3829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_ts', sa.String(length=120), nullable=True, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'created_ts')
    # ### end Alembic commands ###
