"""empty message

Revision ID: d6594a4f3829
Revises: 3a717282ad63
Create Date: 2022-03-08 16:26:53.432431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6594a4f3829'
down_revision = '3a717282ad63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'created_ts',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'created_ts',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
